services:
  nginx-gateway:
    image: nginx:latest
    ports:
      - "8004:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - gateway-network
      - profilesdashboard-rede
      - fitdashboard-rede
networks:
    gateway-network:
      driver: bridge
    profilesdashboard-rede:
      external: true
      name: profilesdashboard-rede
    fitdashboard-rede:
        external: true
        name: fitdashboard-rede