services:
  nginx-gateway:
    image: nginx:latest
    ports:
      - "8004:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - gateway-shared-net
      
networks:
    gateway-shared-net:
      external: true
